### ISSUE TITLE
device_tracker showing stale states 

### ISSUE THREAD

**Issue by arigilder** [kennedyshead/aioasuswrt#15]
I have an AC-RT88U. Running HomeAssistant 0.82 (though I think this may have been happening from before). I perpetually see my devices as set to "home" state, even when they are disconnected. I just checked one device that's not connected, SSH'd to router, did 'ip neigh' and did not see it there.

I notice there is a flurry of activity today on this; is this a KI and is just waiting for a new HA release? Anything else I can do to be of help debugging?

**Comment by kennedyshead** [comment]
Is this something new or have they always been slow to change?

We don't rely solely on `ip neigh` and that could in some cases cause a problem.

Atm. the thing you can do is to test the latest code in this repo and if there are problems you can get logs and so on.
You could also help by setting up a bug-template to use here.

**Comment by arigilder** [comment]
What's the best way to test out this code while running Hassio? Can't figure out how I'd edit the running code...

**Comment by arigilder** [comment]
As an update, I upgraded to HA 0.82.1 which I guess corresponds to aioasuswrt 1.6 but the issue was still not fixed. Trying to figure out how to hack HassIO to let me change the version of aioasuswrt or even better add debug logging...

**Comment by arigilder** [comment]
OK so TL;DR this ended up having nothing to do with aioasuswrt but rather some bugginess in how HA handled stale cached devices. PR at https://github.com/home-assistant/home-assistant/pull/18572 if you're interested in the details.
