### ISSUE TITLE
Not really need all those stats. Just device tracker.

### ISSUE THREAD

**Issue by tanus10** [kennedyshead/aioasuswrt#19]
Recent changes force stat collection from asuswrt a mandatory .
I really have no use for the all those stats, I am just in for the device tracker.
Is there any way to avoid all those data collections?

It's a burden for the router. It produces tons of [asyncssh] logs. I am forced to disable Asuswrt components for the time being.

**Comment by kennedyshead** [comment]
This is not an issue for this package, it should be filed in homeassistant
