### ISSUE TITLE
Code assumes WAN is eth0

### ISSUE THREAD

**Issue by corbinchild** [kennedyshead/aioasuswrt#26]
I have the ASUS RT-N56U router with Padavan's firmware.  The firmware uses the network intervace name "eth3" for WAN.

This is a problem because aioasuswrt assumes that WAN will be "eth0" to obtain upload and download bandwidth statistics.  For example:
`cat /sys/class/net/eth0/statistics/rx_bytes`

Could you please consider adding a config variable so that the interface name can be changed?  The variable could be passed in from Home Assistant.  For example:

```
asuswrt:
  ...
  interface: "eth3"
```

**Comment by pkishino** [comment]
This can be closed now
