### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by roblandry** [kennedyshead/aioasuswrt#29]
Looks like asyncssh needs to be updated to a newer version due to errors in home assistant logs on startup.

https://github.com/ronf/asyncssh/issues/218#issuecomment-506069394

**Comment by kennedyshead** [comment]
I'll do it asap

**Comment by ZetaPhoenix** [comment]
@kennedyshead,

I'm still seeing the errors in the logs. Do you know when the update will be pulled and when Home Assistant will use the new version?

**Comment by roblandry** [comment]
"ASAP"...

**Comment by kennedyshead** [comment]
ASAP = As soon as possible ;)
