### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by JJdeVries** [kennedyshead/aioasuswrt#58]
Is there a specified release cycle, or a plan for creating a new release? I'm waiting for the fixes of #52 to be included in the home assistant installation. (So both a new release, and an update of the core/home-assistant repo would be necessary).

**Comment by kennedyshead** [comment]
Hi!

At the moment I've had a huge workload from work and that is the reason for the delay.

Basically, whats needed is to bump and publish. I had planned to get https://github.com/kennedyshead/aioasuswrt/issues/44 done before release but a minor version could be published as is imo.

**Comment by kennedyshead** [comment]
I also would like to have tests for `async_get_nvram`, `async_get_bytes_total`, `async_get_current_transfer_rates` and `async_add_dns_record`.

**Comment by kennedyshead** [comment]
V1.3.0 is up and on pypi
